extraction:
  cpp:
    prepare:
      packages:
        - python3-pip
        - python3-setuptools
        - python3-wheel
        - libpwquality-dev
        - libfdisk-dev
        - libp11-kit-dev
        - libssl-dev
    after_prepare:
      - pip3 install meson
      - export PATH="$HOME/.local/bin/:$PATH"
  python:
    python_setup:
      version: 3
